# Generated by Django 4.1.3 on 2022-12-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_profile_created_skill_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="social_stackoverflow",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
